import { useState } from 'react';
import { X, Download, FileJson, FileText } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

interface AuditLogModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  fileName: string;
  issueCount: number;
  errorCount: number;
  warningCount: number;
  structureIssues: any[];
  errors: any[];
}

export const AuditLogModal = ({
  open,
  onOpenChange,
  fileName,
  issueCount,
  errorCount,
  warningCount,
  structureIssues,
  errors
}: AuditLogModalProps) => {
  const [format, setFormat] = useState<'json' | 'csv' | 'pdf'>('json');

  const generateAuditLog = () => {
    const timestamp = new Date().toISOString();
    const auditData = {
      metadata: {
        analyzedBy: 'Inspect',
        version: '2.0',
        appName: 'DatumInt',
        appWebsite: 'https://www.datumintapp.com',
        timestamp,
        userAgent: typeof navigator !== 'undefined' ? navigator.userAgent : 'unknown'
      },
      analysis: {
        fileName,
        fileSize: 'calculated',
        analysisStartTime: timestamp,
        analysisEndTime: timestamp,
        analysisStatus: 'completed'
      },
      summary: {
        totalIssuesFound: issueCount,
        criticalErrors: errorCount,
        warnings: warningCount,
        infoItems: errors.filter((e: any) => e.severity === 'info').length
      },
      issues: {
        structural: structureIssues.map((issue: any) => ({
          type: issue.type,
          message: issue.message,
          line: issue.line,
          column: issue.column,
          pattern: issue.pattern,
          suggestedFix: issue.suggestedFix,
          timestamp
        })),
        semantic: errors.map((error: any) => ({
          severity: error.severity,
          category: error.category,
          summary: error.summary,
          line: error.line,
          column: error.column,
          evidence: error.evidence,
          whyItMatters: error.whyItMatters,
          suggestedAction: error.suggestedAction,
          timestamp
        }))
      },
      branding: {
        company: 'DatumInt',
        product: 'Inspect',
        tagline: 'Deterministic Data Quality Analysis',
        website: 'https://www.datumintapp.com'
      }
    };

    if (format === 'json') {
      const blob = new Blob([JSON.stringify(auditData, null, 2)], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `audit-log_${fileName.split('.')[0]}_${Date.now()}.json`;
      a.click();
      URL.revokeObjectURL(url);
      toast.success('Audit log downloaded as JSON');
    } else if (format === 'csv') {
      // Generate CSV format
      let csvContent = 'data:text/csv;charset=utf-8,';
      csvContent += `"DATUMINT AUDIT LOG"\n`;
      csvContent += `"Inspect Analysis Report"\n`;
      csvContent += `"File","${fileName}"\n`;
      csvContent += `"Generated","${new Date().toLocaleString()}"\n`;
      csvContent += `"\n"`;
      csvContent += `"SUMMARY"\n`;
      csvContent += `"Total Issues","${issueCount}"\n`;
      csvContent += `"Critical Errors","${errorCount}"\n`;
      csvContent += `"Warnings","${warningCount}"\n`;
      csvContent += `"\n"`;
      csvContent += `"ISSUES"\n`;
      csvContent += `"Type","Message","Line","Column","Severity"\n`;

      structureIssues.forEach((issue: any) => {
        csvContent += `"Structure","${issue.message}","${issue.line}","${issue.column}","${issue.type}"\n`;
      });

      errors.forEach((error: any) => {
        csvContent += `"Semantic","${error.summary}","${error.line}","${error.column}","${error.severity}"\n`;
      });

      csvContent += `"\n"`;
      csvContent += `"Generated by DatumInt Inspect - https://www.datumintapp.com"\n`;

      const encodedUri = encodeURI(csvContent);
      const link = document.createElement('a');
      link.setAttribute('href', encodedUri);
      link.setAttribute('download', `audit-log_${fileName.split('.')[0]}_${Date.now()}.csv`);
      link.click();
      toast.success('Audit log downloaded as CSV');
    } else if (format === 'pdf') {
      const pdfHtmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DatumInt Inspect Audit Log</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; background: #f8fafc; color: #1e293b; line-height: 1.6; }
        .container { max-width: 900px; margin: 0 auto; padding: 40px 20px; }
        header { border-bottom: 2px solid #e2e8f0; padding-bottom: 30px; margin-bottom: 30px; }
        .logo { font-size: 28px; font-weight: bold; margin-bottom: 10px; color: #3b82f6; }
        .tagline { color: #64748b; font-size: 14px; }
        .metadata { background: #f1f5f9; border-radius: 8px; padding: 20px; margin-bottom: 30px; display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
        .meta-item { }
        .meta-label { color: #64748b; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; }
        .meta-value { color: #1e293b; font-weight: 600; margin-top: 5px; }
        .summary { background: #f1f5f9; border-radius: 8px; padding: 20px; margin-bottom: 30px; display: grid; grid-template-columns: repeat(4, 1fr); gap: 20px; }
        .stat-card { }
        .stat-number { font-size: 32px; font-weight: bold; color: #3b82f6; }
        .stat-label { color: #64748b; font-size: 13px; margin-top: 5px; }
        .issues-section { margin-bottom: 40px; }
        .section-title { font-size: 20px; font-weight: bold; margin-bottom: 20px; color: #1e293b; border-bottom: 1px solid #e2e8f0; padding-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; }
        th { background: #f1f5f9; color: #475569; text-align: left; padding: 12px; font-size: 13px; font-weight: 600; border-bottom: 2px solid #e2e8f0; }
        td { padding: 12px; border-bottom: 1px solid #e2e8f0; font-size: 12px; }
        tr:hover { background: rgba(0, 0, 0, 0.02); }
        .severity-error { color: #dc2626; font-weight: 600; }
        .severity-warning { color: #ea580c; font-weight: 600; }
        .severity-info { color: #3b82f6; font-weight: 600; }
        .type-structure { color: #7c3aed; font-weight: 600; }
        .type-semantic { color: #06b6d4; font-weight: 600; }
        footer { border-top: 1px solid #e2e8f0; padding-top: 20px; margin-top: 40px; text-align: center; color: #94a3b8; font-size: 12px; }
        .footer-brand { font-weight: 600; color: #64748b; margin-bottom: 5px; }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <div class="logo">📋 Audit Log</div>
      <p class="tagline">Inspect Analysis Audit Trail</p>
        </header>

        <div class="metadata">
            <div class="meta-item">
                <div class="meta-label">Analyzed File</div>
                <div class="meta-value">${fileName}</div>
            </div>
            <div class="meta-item">
                <div class="meta-label">Generated</div>
                <div class="meta-value">${new Date().toLocaleString()}</div>
            </div>
            <div class="meta-item">
                <div class="meta-label">Analyzer</div>
              <div class="meta-value">DatumInt Inspect v2.0</div>
            </div>
            <div class="meta-item">
                <div class="meta-label">Analysis Status</div>
                <div class="meta-value">Completed</div>
            </div>
        </div>

        <div class="summary">
            <div class="stat-card">
                <div class="stat-number">${issueCount}</div>
                <div class="stat-label">Total Issues</div>
            </div>
            <div class="stat-card">
                <div class="stat-number" style="color: #dc2626;">${errorCount}</div>
                <div class="stat-label">Critical Errors</div>
            </div>
            <div class="stat-card">
                <div class="stat-number" style="color: #ea580c;">${warningCount}</div>
                <div class="stat-label">Warnings</div>
            </div>
            <div class="stat-card">
                <div class="stat-number" style="color: #3b82f6;">${errors.filter((e: any) => e.severity === 'info').length}</div>
                <div class="stat-label">Info Items</div>
            </div>
        </div>

        <div class="issues-section">
            <div class="section-title">Issues Detected</div>
            ${issueCount > 0 ? `
            <table>
                <thead>
                    <tr>
                        <th>Type</th>
                        <th>Message</th>
                        <th>Line</th>
                        <th>Column</th>
                        <th>Severity</th>
                    </tr>
                </thead>
                <tbody>
                    ${structureIssues.map((issue: any) => `
                    <tr>
                        <td><span class="type-structure">STRUCTURE</span></td>
                        <td>${issue.message}</td>
                        <td>${issue.line || '-'}</td>
                        <td>${issue.column || '-'}</td>
                        <td><span class="severity-${issue.type.toLowerCase()}">${issue.type}</span></td>
                    </tr>
                    `).join('')}
                    ${errors.map((error: any) => `
                    <tr>
                        <td><span class="type-semantic">SEMANTIC</span></td>
                        <td>${error.summary}</td>
                        <td>${error.line || '-'}</td>
                        <td>${error.column || '-'}</td>
                        <td><span class="severity-${error.severity || 'info'}">${(error.severity || 'info').toUpperCase()}</span></td>
                    </tr>
                    `).join('')}
                </tbody>
            </table>
            ` : '<p style="color: #64748b;">No issues found - file passed all checks!</p>'}
        </div>

        <footer>
          <div class="footer-brand">DatumInt • Inspect</div>
            <p>Deterministic Data Quality Analysis</p>
            <p style="margin-top: 10px;">https://www.datumintapp.com</p>
        </footer>
    </div>
</body>
</html>`;
      
      const element = document.createElement('div');
      element.innerHTML = pdfHtmlContent;
      element.style.display = 'none';
      document.body.appendChild(element);

      html2canvas(element, { scale: 2, useCORS: true }).then((canvas) => {
        const imgData = canvas.toDataURL('image/png');
        const pdf = new jsPDF('p', 'mm', 'a4');
        const imgWidth = 210;
        const imgHeight = (canvas.height * imgWidth) / canvas.width;
        let heightLeft = imgHeight;
        let position = 0;

        pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
        heightLeft -= 297;

        while (heightLeft >= 0) {
          position = heightLeft - imgHeight;
          pdf.addPage();
          pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
          heightLeft -= 297;
        }

        pdf.save(`audit-log_${fileName.split('.')[0]}_${Date.now()}.pdf`);
        document.body.removeChild(element);
        toast.success('Audit log downloaded as PDF');
      });
      return;
    }

    onOpenChange(false);
  };

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4">
      <div className="mx-auto bg-[#1F2326] border border-[#2B2F33] rounded-md shadow-2xl text-sm text-[#D1D5DB] max-w-sm w-full">
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-[#2B2F33]">
          <h2 className="text-lg font-semibold text-[#D1D5DB]">Download Audit Log</h2>
          <button
            onClick={() => onOpenChange(false)}
            className="text-[#94A3B8] hover:text-[#D1D5DB] transition-colors"
            aria-label="Close audit modal"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Content */}
        <div className="px-5 py-4 space-y-4">
          {/* Summary */}
          <div className="bg-[#26292C] border border-[#2B2F33] rounded p-4 space-y-2 text-sm">
            <div className="flex justify-between">
              <span className="text-[#9CA3AF]">File</span>
              <span className="text-[#D1D5DB] font-medium">{fileName}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-[#9CA3AF]">Total Issues</span>
              <span className="text-[#D1D5DB] font-medium">{issueCount}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-[#9CA3AF]">Errors</span>
              <span className="text-red-400 font-medium">{errorCount}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-[#9CA3AF]">Warnings</span>
              <span className="text-yellow-400 font-medium">{warningCount}</span>
            </div>
            <div className="flex justify-between text-xs pt-2 border-t border-[#2B2F33]">
              <span className="text-[#9CA3AF]">Timestamp</span>
              <span className="text-[#9CA3AF]">{new Date().toLocaleString()}</span>
            </div>
          </div>

          {/* Format Selection */}
          <div className="space-y-2">
            <label className="text-sm font-medium text-[#D1D5DB]">Export Format</label>
            <div className="flex gap-2">
              <button
                onClick={() => setFormat('json')}
                className={`flex-1 flex items-center justify-center gap-2 px-3 py-2 rounded text-sm font-medium transition-colors ${
                  format === 'json'
                    ? 'bg-[#2B3840] text-[#D1D5DB] border border-[#37474F]'
                    : 'bg-[#26292C] text-[#C7CED6] hover:bg-[#2B2F33]'
                }`}
              >
                <FileJson className="h-4 w-4" />
                JSON
              </button>
              <button
                onClick={() => setFormat('csv')}
                className={`flex-1 flex items-center justify-center gap-2 px-3 py-2 rounded text-sm font-medium transition-colors ${
                  format === 'csv'
                    ? 'bg-[#2B3840] text-[#D1D5DB] border border-[#37474F]'
                    : 'bg-[#26292C] text-[#C7CED6] hover:bg-[#2B2F33]'
                }`}
              >
                <FileText className="h-4 w-4" />
                CSV
              </button>
              <button
                onClick={() => setFormat('pdf')}
                className={`flex-1 flex items-center justify-center gap-2 px-3 py-2 rounded text-sm font-medium transition-colors ${
                  format === 'pdf'
                    ? 'bg-[#2B3840] text-[#D1D5DB] border border-[#37474F]'
                    : 'bg-[#26292C] text-[#C7CED6] hover:bg-[#2B2F33]'
                }`}
              >
                <FileText className="h-4 w-4" />
                PDF
              </button>
            </div>
          </div>

          {/* Download Button */}
          <button
            onClick={generateAuditLog}
            className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-[#3B82F6] hover:bg-[#2563EB] rounded text-white font-medium transition-colors"
          >
            <Download className="h-4 w-4" />
            Download Audit Log
          </button>

          {/* Branding Footer */}
          <div className="pt-3 border-t border-[#2B2F33] text-center text-xs text-[#9CA3AF] space-y-1">
            <p>DatumInt • Inspect Analysis</p>
            <p>Professional Data Quality Auditing</p>
          </div>
        </div>
      </div>
    </div>
  );
};
