import { useState } from 'react';
import { X, Download, FileJson, FileText } from 'lucide-react';
import { toast } from 'sonner';

interface ExportModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  fileName: string;
  content: string;
  issues: any[];
  analysisResult: any;
}

export const ExportModal = ({
  open,
  onOpenChange,
  fileName,
  content,
  issues,
  analysisResult
}: ExportModalProps) => {
  const [format, setFormat] = useState<'json' | 'csv' | 'html'>('json');

  const escapeCsv = (val: any) => {
    const s = val === null || val === undefined ? '' : String(val);
    const escaped = s.replace(/"/g, '""');
    return /[",\n]/.test(escaped) ? `"${escaped}"` : escaped;
  };

  const handleExport = () => {
    const timestamp = new Date().toISOString();
    const baseFileName = fileName.split('.')[0];

    if (format === 'json') {
      const report = {
        metadata: {
          exportedBy: 'Inspect',
          version: '2.0',
          appName: 'DatumInt',
          exportDate: timestamp,
          website: 'https://datumint.vercel.app'
        },
        file: {
          name: fileName,
          content: content,
          charset: 'utf-8'
        },
        analysis: analysisResult,
        issues: issues,
        summary: {
          totalIssues: issues.length,
          byCategory: issues.reduce((acc: any, issue: any) => {
            acc[issue.category] = (acc[issue.category] || 0) + 1;
            return acc;
          }, {}),
          bySeverity: issues.reduce((acc: any, issue: any) => {
            acc[issue.severity || 'unknown'] = (acc[issue.severity || 'unknown'] || 0) + 1;
            return acc;
          }, {})
        },
        branding: {
          company: 'DatumInt',
          product: 'Inspect',
          tagline: 'Deterministic Data Quality Analysis',
          website: 'https://datumint.vercel.app'
        }
      };

      const blob = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `inspect-report_${baseFileName}_${Date.now()}.json`;
      a.click();
      URL.revokeObjectURL(url);
      toast.success('Report exported as JSON');
    } else if (format === 'csv') {
      const rows: string[] = [];
      rows.push(['DATUMINT - INSPECT ANALYSIS REPORT'].map(escapeCsv).join(','));
      rows.push(['File', fileName].map(escapeCsv).join(','));
      rows.push(['Generated', new Date().toLocaleString()].map(escapeCsv).join(','));
      rows.push(['Total Issues', String(issues.length)].map(escapeCsv).join(','));
      rows.push('');
      rows.push(['Line', 'Column', 'Category', 'Severity', 'Summary', 'Evidence'].map(escapeCsv).join(','));

      issues.forEach((issue: any) => {
        const line = issue.line ?? '';
        const column = issue.column ?? '';
        const category = issue.category ?? '';
        const severity = issue.severity ?? 'info';
        const summary = issue.summary ?? issue.message ?? '';
        const evidence = typeof issue.evidence === 'string' ? issue.evidence : JSON.stringify(issue.evidence || '');
        rows.push([
          line,
          column,
          category,
          severity,
          summary,
          evidence,
        ].map(escapeCsv).join(','));
      });

      rows.push('');
      rows.push(['Generated by DatumInt Inspect - https://datumint.vercel.app'].map(escapeCsv).join(','));

      const csvBlob = new Blob([rows.join('\n')], { type: 'text/csv;charset=utf-8;' });
      const url = URL.createObjectURL(csvBlob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `inspect-report_${baseFileName}_${Date.now()}.csv`;
      a.click();
      URL.revokeObjectURL(url);
      toast.success('Report exported as CSV');
    } else if (format === 'html') {
      const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DatumInt Inspect Analysis Report</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; background: #0f172a; color: #e2e8f0; line-height: 1.6; }
        .container { max-width: 900px; margin: 0 auto; padding: 40px 20px; }
        header { border-bottom: 2px solid #1e293b; padding-bottom: 30px; margin-bottom: 30px; }
        .logo { font-size: 28px; font-weight: bold; margin-bottom: 10px; color: #60a5fa; }
        .tagline { color: #94a3b8; font-size: 14px; }
        .metadata { background: #1e293b; border-radius: 8px; padding: 20px; margin-bottom: 30px; display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
        .meta-item { }
        .meta-label { color: #94a3b8; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; }
        .meta-value { color: #e2e8f0; font-weight: 600; margin-top: 5px; }
        .summary { background: #1e293b; border-radius: 8px; padding: 20px; margin-bottom: 30px; display: grid; grid-template-columns: repeat(4, 1fr); gap: 20px; }
        .stat-card { }
        .stat-number { font-size: 32px; font-weight: bold; color: #60a5fa; }
        .stat-label { color: #94a3b8; font-size: 13px; margin-top: 5px; }
        .issues-section { margin-bottom: 40px; }
        .section-title { font-size: 20px; font-weight: bold; margin-bottom: 20px; color: #e2e8f0; border-bottom: 1px solid #334155; padding-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; }
        th { background: #1e293b; color: #cbd5e1; text-align: left; padding: 12px; font-size: 13px; font-weight: 600; border-bottom: 2px solid #334155; }
        td { padding: 12px; border-bottom: 1px solid #334155; }
        tr:hover { background: rgba(255, 255, 255, 0.02); }
        .severity-error { color: #f87171; }
        .severity-warning { color: #facc15; }
        .severity-info { color: #60a5fa; }
        footer { border-top: 1px solid #334155; padding-top: 20px; margin-top: 40px; text-align: center; color: #64748b; font-size: 12px; }
        .footer-brand { font-weight: 600; color: #94a3b8; margin-bottom: 5px; }
    </style>
</head>
<body>
    <div class="container">
        <header>
      <div class="logo">🔍 Inspect</div>
            <p class="tagline">Professional Data Quality Analysis Report</p>
        </header>

        <div class="metadata">
            <div class="meta-item">
                <div class="meta-label">Analyzed File</div>
                <div class="meta-value">${fileName}</div>
            </div>
            <div class="meta-item">
                <div class="meta-label">Generated</div>
                <div class="meta-value">${new Date().toLocaleString()}</div>
            </div>
            <div class="meta-item">
                <div class="meta-label">Analyzer</div>
              <div class="meta-value">DatumInt Inspect v2.0</div>
            </div>
            <div class="meta-item">
                <div class="meta-label">Analysis Type</div>
                <div class="meta-value">Deterministic Quality Check</div>
            </div>
        </div>

        <div class="summary">
            <div class="stat-card">
                <div class="stat-number">${issues.length}</div>
                <div class="stat-label">Total Issues</div>
            </div>
            <div class="stat-card">
                <div class="stat-number" style="color: #f87171;">${issues.filter((i: any) => i.severity === 'error').length}</div>
                <div class="stat-label">Errors</div>
            </div>
            <div class="stat-card">
                <div class="stat-number" style="color: #facc15;">${issues.filter((i: any) => i.severity === 'warning').length}</div>
                <div class="stat-label">Warnings</div>
            </div>
            <div class="stat-card">
                <div class="stat-number" style="color: #60a5fa;">${issues.filter((i: any) => i.severity === 'info').length}</div>
                <div class="stat-label">Info Items</div>
            </div>
        </div>

        <div class="issues-section">
            <div class="section-title">Issues Found</div>
            ${issues.length > 0 ? `
            <table>
                <thead>
                    <tr>
                        <th>Line</th>
                        <th>Column</th>
                        <th>Category</th>
                        <th>Severity</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    ${issues.map((issue: any) => `
                    <tr>
                        <td>${issue.line || '-'}</td>
                        <td>${issue.column || '-'}</td>
                        <td>${issue.category || '-'}</td>
                        <td><span class="severity-${issue.severity || 'info'}">${(issue.severity || 'info').toUpperCase()}</span></td>
                        <td>${issue.summary || issue.message || ''}</td>
                    </tr>
                    `).join('')}
                </tbody>
            </table>
            ` : '<p style="color: #94a3b8;">No issues found - file passed all checks!</p>'}
        </div>

        <footer>
          <div class="footer-brand">DatumInt • Inspect</div>
            <p>Deterministic Data Quality Analysis</p>
            <p style="margin-top: 10px;"><a href="https://datumint.vercel.app" style="color: #60a5fa;">Visit DatumInt</a></p>
        </footer>
    </div>
</body>
</html>`;

      const blob = new Blob([htmlContent], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `inspect-report_${baseFileName}_${Date.now()}.html`;
      a.click();
      URL.revokeObjectURL(url);
      toast.success('Report exported as HTML');
    }

    onOpenChange(false);
  };

  if (!open) return null;

  const formatDescriptions: Record<string, string> = {
    json: 'Full structured data including file content, analysis details, and all issues',
    csv: 'Spreadsheet-compatible format for data analysis and archiving',
    html: 'Beautiful branded report viewable in any web browser'
  };
  return (
    <div className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4">
      <div className="mx-auto bg-[#1F2326] border border-[#2B2F33] rounded-md shadow-2xl text-sm text-[#D1D5DB] max-w-lg w-full">
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-[#2B2F33]">
          <h2 className="text-lg font-semibold text-[#D1D5DB]">Export Analysis Report</h2>
          <button
            onClick={() => onOpenChange(false)}
            className="text-[#94A3B8] hover:text-[#D1D5DB] transition-colors"
            aria-label="Close export modal"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Content */}
        <div className="px-5 py-4 space-y-4">
          {/* File Info */}
          <div className="bg-[#26292C] border border-[#2B2F33] rounded p-4">
            <p className="text-sm text-[#9CA3AF]">Exporting</p>
            <p className="text-[#D1D5DB] font-semibold">{fileName}</p>
          </div>

          {/* Format Selection */}
          <div className="space-y-3">
            <label className="text-sm font-medium text-[#D1D5DB]">Export Format</label>
            <div className="space-y-2">
              {(['json', 'csv', 'html'] as const).map((fmt) => (
                <label key={fmt} className="flex items-start gap-3 cursor-pointer p-3 rounded border border-[#2B2F33] hover:border-[#37474F] transition-colors">
                  <input
                    type="radio"
                    name="format"
                    value={fmt}
                    checked={format === fmt}
                    onChange={(e) => setFormat(e.target.value as any)}
                    className="mt-1"
                  />
                  <div className="flex-1">
                    <div className="font-medium text-[#D1D5DB] capitalize flex items-center gap-2">
                      {fmt === 'json' && <FileJson className="h-4 w-4 text-[#C7CED6]" />}
                      {fmt === 'csv' && <FileText className="h-4 w-4 text-[#C7CED6]" />}
                      {fmt === 'html' && <FileText className="h-4 w-4 text-[#C7CED6]" />}
                      {fmt.toUpperCase()}
                    </div>
                    <p className="text-sm text-[#9CA3AF]">{formatDescriptions[fmt]}</p>
                  </div>
                </label>
              ))}
            </div>
          </div>

          {/* Export Button */}
          <button
            onClick={handleExport}
            className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-[#3B82F6] hover:bg-[#2563EB] rounded text-white font-medium transition-colors"
          >
            <Download className="h-4 w-4" />
            Export as {format.toUpperCase()}
          </button>

          {/* Branding Footer */}
          <div className="pt-3 border-t border-[#2B2F33] text-center text-xs text-[#9CA3AF] space-y-1">
            <p>Powered by DatumInt • Inspect</p>
            <p>Professional Data Quality Analysis</p>
          </div>
        </div>
      </div>
    </div>
  );
};
