import { useState } from 'react';
import { X, Download, FileJson, FileText } from 'lucide-react';
import { toast } from 'sonner';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

interface ExportModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  fileName: string;
  content: string;
  issues: any[];
  analysisResult: any;
}

export const ExportModal = ({
  open,
  onOpenChange,
  fileName,
  content,
  issues,
  analysisResult
}: ExportModalProps) => {
  const [format, setFormat] = useState<'json' | 'csv' | 'html' | 'pdf'>('json');

  const handleExport = () => {
    const timestamp = new Date().toISOString();
    const baseFileName = fileName.split('.')[0];

    if (format === 'json') {
      const report = {
        metadata: {
          exportedBy: 'Detective D',
          version: '2.0',
          appName: 'DatumInt',
          exportDate: timestamp,
          website: 'https://datumint.vercel.app'
        },
        file: {
          name: fileName,
          content: content,
          charset: 'utf-8'
        },
        analysis: analysisResult,
        issues: issues,
        summary: {
          totalIssues: issues.length,
          byCategory: issues.reduce((acc: any, issue: any) => {
            acc[issue.category] = (acc[issue.category] || 0) + 1;
            return acc;
          }, {}),
          bySeverity: issues.reduce((acc: any, issue: any) => {
            acc[issue.severity || 'unknown'] = (acc[issue.severity || 'unknown'] || 0) + 1;
            return acc;
          }, {})
        },
        branding: {
          company: 'DatumInt',
          product: 'Detective D',
          tagline: 'Deterministic Data Quality Analysis',
          website: 'https://datumint.vercel.app'
        }
      };

      const blob = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `detective-d-report_${baseFileName}_${Date.now()}.json`;
      a.click();
      URL.revokeObjectURL(url);
      toast.success('Report exported as JSON');
    } else if (format === 'csv') {
      let csvContent = 'data:text/csv;charset=utf-8,';
      csvContent += `"DATUMINT - DETECTIVE D ANALYSIS REPORT"\n`;
      csvContent += `"File","${fileName}"\n`;
      csvContent += `"Generated","${new Date().toLocaleString()}"\n`;
      csvContent += `"Total Issues","${issues.length}"\n`;
      csvContent += `"\n"`;
      csvContent += `"ISSUES DETAIL"\n`;
      csvContent += `"Line","Column","Category","Severity","Summary","Evidence"\n`;

      issues.forEach((issue: any) => {
        const line = issue.line || '';
        const column = issue.column || '';
        const category = issue.category || '';
        const severity = issue.severity || 'info';
        const summary = (issue.summary || '').replace(/"/g, '""');
        const evidence = (issue.evidence || '').replace(/"/g, '""');
        csvContent += `"${line}","${column}","${category}","${severity}","${summary}","${evidence}"\n`;
      });

      csvContent += `"\n"`;
      csvContent += `"Generated by DatumInt Detective D - https://datumint.vercel.app"\n`;

      const encodedUri = encodeURI(csvContent);
      const link = document.createElement('a');
      link.setAttribute('href', encodedUri);
      link.setAttribute('download', `detective-d-report_${baseFileName}_${Date.now()}.csv`);
      link.click();
      toast.success('Report exported as CSV');
    } else if (format === 'html') {
      const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DatumInt Detective D Analysis Report</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; background: #0f172a; color: #e2e8f0; line-height: 1.6; }
        .container { max-width: 900px; margin: 0 auto; padding: 40px 20px; }
        header { border-bottom: 2px solid #1e293b; padding-bottom: 30px; margin-bottom: 30px; }
        .logo { font-size: 28px; font-weight: bold; margin-bottom: 10px; color: #60a5fa; }
        .tagline { color: #94a3b8; font-size: 14px; }
        .metadata { background: #1e293b; border-radius: 8px; padding: 20px; margin-bottom: 30px; display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
        .meta-item { }
        .meta-label { color: #94a3b8; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; }
        .meta-value { color: #e2e8f0; font-weight: 600; margin-top: 5px; }
        .summary { background: #1e293b; border-radius: 8px; padding: 20px; margin-bottom: 30px; display: grid; grid-template-columns: repeat(4, 1fr); gap: 20px; }
        .stat-card { }
        .stat-number { font-size: 32px; font-weight: bold; color: #60a5fa; }
        .stat-label { color: #94a3b8; font-size: 13px; margin-top: 5px; }
        .issues-section { margin-bottom: 40px; }
        .section-title { font-size: 20px; font-weight: bold; margin-bottom: 20px; color: #e2e8f0; border-bottom: 1px solid #334155; padding-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; }
        th { background: #1e293b; color: #cbd5e1; text-align: left; padding: 12px; font-size: 13px; font-weight: 600; border-bottom: 2px solid #334155; }
        td { padding: 12px; border-bottom: 1px solid #334155; }
        tr:hover { background: rgba(255, 255, 255, 0.02); }
        .severity-error { color: #f87171; }
        .severity-warning { color: #facc15; }
        .severity-info { color: #60a5fa; }
        footer { border-top: 1px solid #334155; padding-top: 20px; margin-top: 40px; text-align: center; color: #64748b; font-size: 12px; }
        .footer-brand { font-weight: 600; color: #94a3b8; margin-bottom: 5px; }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <div class="logo">🔍 Detective D</div>
            <p class="tagline">Professional Data Quality Analysis Report</p>
        </header>

        <div class="metadata">
            <div class="meta-item">
                <div class="meta-label">Analyzed File</div>
                <div class="meta-value">${fileName}</div>
            </div>
            <div class="meta-item">
                <div class="meta-label">Generated</div>
                <div class="meta-value">${new Date().toLocaleString()}</div>
            </div>
            <div class="meta-item">
                <div class="meta-label">Analyzer</div>
                <div class="meta-value">DatumInt Detective D v2.0</div>
            </div>
            <div class="meta-item">
                <div class="meta-label">Analysis Type</div>
                <div class="meta-value">Deterministic Quality Check</div>
            </div>
        </div>

        <div class="summary">
            <div class="stat-card">
                <div class="stat-number">${issues.length}</div>
                <div class="stat-label">Total Issues</div>
            </div>
            <div class="stat-card">
                <div class="stat-number" style="color: #f87171;">${issues.filter((i: any) => i.severity === 'error').length}</div>
                <div class="stat-label">Errors</div>
            </div>
            <div class="stat-card">
                <div class="stat-number" style="color: #facc15;">${issues.filter((i: any) => i.severity === 'warning').length}</div>
                <div class="stat-label">Warnings</div>
            </div>
            <div class="stat-card">
                <div class="stat-number" style="color: #60a5fa;">${issues.filter((i: any) => i.severity === 'info').length}</div>
                <div class="stat-label">Info Items</div>
            </div>
        </div>

        <div class="issues-section">
            <div class="section-title">Issues Found</div>
            ${issues.length > 0 ? `
            <table>
                <thead>
                    <tr>
                        <th>Line</th>
                        <th>Column</th>
                        <th>Category</th>
                        <th>Severity</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    ${issues.map((issue: any) => `
                    <tr>
                        <td>${issue.line || '-'}</td>
                        <td>${issue.column || '-'}</td>
                        <td>${issue.category || '-'}</td>
                        <td><span class="severity-${issue.severity || 'info'}">${(issue.severity || 'info').toUpperCase()}</span></td>
                        <td>${issue.summary || issue.message || ''}</td>
                    </tr>
                    `).join('')}
                </tbody>
            </table>
            ` : '<p style="color: #94a3b8;">No issues found - file passed all checks!</p>'}
        </div>

        <footer>
            <div class="footer-brand">DatumInt • Detective D</div>
            <p>Deterministic Data Quality Analysis</p>
            <p style="margin-top: 10px;"><a href="https://datumint.vercel.app" style="color: #60a5fa;">Visit DatumInt</a></p>
        </footer>
    </div>
</body>
</html>`;

      const blob = new Blob([htmlContent], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `detective-d-report_${baseFileName}_${Date.now()}.html`;
      a.click();
      URL.revokeObjectURL(url);
      toast.success('Report exported as HTML');
    } else if (format === 'pdf') {
      const pdfHtmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DatumInt Detective D Analysis Report</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; background: #f8fafc; color: #1e293b; line-height: 1.6; }
        .container { max-width: 900px; margin: 0 auto; padding: 40px 20px; }
        header { border-bottom: 2px solid #e2e8f0; padding-bottom: 30px; margin-bottom: 30px; }
        .logo { font-size: 28px; font-weight: bold; margin-bottom: 10px; color: #3b82f6; }
        .tagline { color: #64748b; font-size: 14px; }
        .metadata { background: #f1f5f9; border-radius: 8px; padding: 20px; margin-bottom: 30px; display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
        .meta-item { }
        .meta-label { color: #64748b; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; }
        .meta-value { color: #1e293b; font-weight: 600; margin-top: 5px; }
        .summary { background: #f1f5f9; border-radius: 8px; padding: 20px; margin-bottom: 30px; display: grid; grid-template-columns: repeat(4, 1fr); gap: 20px; }
        .stat-card { }
        .stat-number { font-size: 32px; font-weight: bold; color: #3b82f6; }
        .stat-label { color: #64748b; font-size: 13px; margin-top: 5px; }
        .issues-section { margin-bottom: 40px; }
        .section-title { font-size: 20px; font-weight: bold; margin-bottom: 20px; color: #1e293b; border-bottom: 1px solid #e2e8f0; padding-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; }
        th { background: #f1f5f9; color: #475569; text-align: left; padding: 12px; font-size: 13px; font-weight: 600; border-bottom: 2px solid #e2e8f0; }
        td { padding: 12px; border-bottom: 1px solid #e2e8f0; }
        tr:hover { background: rgba(0, 0, 0, 0.02); }
        .severity-error { color: #dc2626; font-weight: 600; }
        .severity-warning { color: #ea580c; font-weight: 600; }
        .severity-info { color: #3b82f6; font-weight: 600; }
        footer { border-top: 1px solid #e2e8f0; padding-top: 20px; margin-top: 40px; text-align: center; color: #94a3b8; font-size: 12px; }
        .footer-brand { font-weight: 600; color: #64748b; margin-bottom: 5px; }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <div class="logo">🔍 Detective D</div>
            <p class="tagline">Professional Data Quality Analysis Report</p>
        </header>

        <div class="metadata">
            <div class="meta-item">
                <div class="meta-label">Analyzed File</div>
                <div class="meta-value">${fileName}</div>
            </div>
            <div class="meta-item">
                <div class="meta-label">Generated</div>
                <div class="meta-value">${new Date().toLocaleString()}</div>
            </div>
            <div class="meta-item">
                <div class="meta-label">Analyzer</div>
                <div class="meta-value">DatumInt Detective D v2.0</div>
            </div>
            <div class="meta-item">
                <div class="meta-label">Analysis Type</div>
                <div class="meta-value">Deterministic Quality Check</div>
            </div>
        </div>

        <div class="summary">
            <div class="stat-card">
                <div class="stat-number">${issues.length}</div>
                <div class="stat-label">Total Issues</div>
            </div>
            <div class="stat-card">
                <div class="stat-number" style="color: #dc2626;">${issues.filter((i: any) => i.severity === 'error').length}</div>
                <div class="stat-label">Errors</div>
            </div>
            <div class="stat-card">
                <div class="stat-number" style="color: #ea580c;">${issues.filter((i: any) => i.severity === 'warning').length}</div>
                <div class="stat-label">Warnings</div>
            </div>
            <div class="stat-card">
                <div class="stat-number" style="color: #3b82f6;">${issues.filter((i: any) => i.severity === 'info').length}</div>
                <div class="stat-label">Info Items</div>
            </div>
        </div>

        <div class="issues-section">
            <div class="section-title">Issues Found</div>
            ${issues.length > 0 ? `
            <table>
                <thead>
                    <tr>
                        <th>Line</th>
                        <th>Column</th>
                        <th>Category</th>
                        <th>Severity</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    ${issues.map((issue: any) => `
                    <tr>
                        <td>${issue.line || '-'}</td>
                        <td>${issue.column || '-'}</td>
                        <td>${issue.category || '-'}</td>
                        <td><span class="severity-${issue.severity || 'info'}">${(issue.severity || 'info').toUpperCase()}</span></td>
                        <td>${issue.summary || issue.message || ''}</td>
                    </tr>
                    `).join('')}
                </tbody>
            </table>
            ` : '<p style="color: #64748b;">No issues found - file passed all checks!</p>'}
        </div>

        <footer>
            <div class="footer-brand">DatumInt • Detective D</div>
            <p>Deterministic Data Quality Analysis</p>
            <p style="margin-top: 10px;">https://datumint.vercel.app</p>
        </footer>
    </div>
</body>
</html>`;
      
      const element = document.createElement('div');
      element.innerHTML = pdfHtmlContent;
      element.style.display = 'none';
      document.body.appendChild(element);

      html2canvas(element, { scale: 2, useCORS: true }).then((canvas) => {
        const imgData = canvas.toDataURL('image/png');
        const pdf = new jsPDF('p', 'mm', 'a4');
        const imgWidth = 210;
        const imgHeight = (canvas.height * imgWidth) / canvas.width;
        let heightLeft = imgHeight;
        let position = 0;

        pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
        heightLeft -= 297;

        while (heightLeft >= 0) {
          position = heightLeft - imgHeight;
          pdf.addPage();
          pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
          heightLeft -= 297;
        }

        pdf.save(`detective-d-report_${baseFileName}_${Date.now()}.pdf`);
        document.body.removeChild(element);
        toast.success('Report exported as PDF');
      });
      return;
    }

    onOpenChange(false);
  };

  if (!open) return null;

  const formatDescriptions: Record<string, string> = {
    json: 'Full structured data including file content, analysis details, and all issues',
    csv: 'Spreadsheet-compatible format for data analysis and archiving',
    html: 'Beautiful branded report viewable in any web browser',
    pdf: 'Professional PDF report with DatumInt branding and formatting'
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4">
      <div className="bg-slate-950 border border-slate-800 rounded-lg shadow-xl max-w-lg w-full">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-800">
          <h2 className="text-lg font-semibold text-slate-100">Export Analysis Report</h2>
          <button
            onClick={() => onOpenChange(false)}
            className="text-slate-400 hover:text-slate-200 transition-colors"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Content */}
        <div className="px-6 py-4 space-y-4">
          {/* File Info */}
          <div className="bg-slate-900 border border-slate-800 rounded p-4">
            <p className="text-sm text-slate-400">Exporting</p>
            <p className="text-slate-100 font-semibold">{fileName}</p>
          </div>

          {/* Format Selection */}
          <div className="space-y-3">
            <label className="text-sm font-medium text-slate-100">Export Format</label>
            <div className="space-y-2">
              {(['json', 'csv', 'html', 'pdf'] as const).map((fmt) => (
                <label key={fmt} className="flex items-start gap-3 cursor-pointer p-3 rounded border border-slate-800 hover:border-slate-700 transition-colors">
                  <input
                    type="radio"
                    name="format"
                    value={fmt}
                    checked={format === fmt}
                    onChange={(e) => setFormat(e.target.value as any)}
                    className="mt-1"
                  />
                  <div className="flex-1">
                    <div className="font-medium text-slate-100 capitalize flex items-center gap-2">
                      {fmt === 'json' && <FileJson className="h-4 w-4" />}
                      {fmt === 'csv' && <FileText className="h-4 w-4" />}
                      {fmt === 'html' && <FileText className="h-4 w-4" />}
                      {fmt.toUpperCase()}
                    </div>
                    <p className="text-sm text-slate-400">{formatDescriptions[fmt]}</p>
                  </div>
                </label>
              ))}
            </div>
          </div>

          {/* Export Button */}
          <button
            onClick={handleExport}
            className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-primary hover:bg-primary/90 rounded text-primary-foreground font-medium transition-colors"
          >
            <Download className="h-4 w-4" />
            Export as {format.toUpperCase()}
          </button>

          {/* Branding Footer */}
          <div className="pt-3 border-t border-slate-800 text-center text-xs text-slate-500 space-y-1">
            <p>Powered by DatumInt • Detective D</p>
            <p>Professional Data Quality Analysis</p>
          </div>
        </div>
      </div>
    </div>
  );
};
